[package]
name = "rodrick160/quilt"
description = "A module importer with simple syntax and support for recursive imports."
version = "0.3.1"
license = "MPL 2.0"
authors = ["Sebastian Seifert"]
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
exclude = [".gitignore", ".vscode"]